# Modify the next line to specify your own application instance.
application: bigquery-sensors
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /dashboard/.*
  script: dashboard.app
  login: admin

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /data/.*
  script: dashboard.app

- url: /static
  static_dir: static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*

